%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\IROA\IROALot6\addToLib.xlsx Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/03 10:50:29

%% Import the data
[~, ~, raw] = xlsread('E:\IROA\IROALot6\addToLib.xlsx','Sheet1');
raw(1,:)=[];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2]);
raw = raw(:,[3,4,5,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Name = cellVectors(:,1);
MF = cellVectors(:,2);
nC = data(:,1);
C13mz = data(:,2);
Time = data(:,3);
Mode = data(:,4);

%% Clear temporary variables
clearvars data raw cellVectors;